<?php

namespace App\Services;

use App\Models\DkimKey;
use App\Models\Domain;
use App\Models\DnsZone;
use App\Models\AuditLog;
use App\Shell\SudoExecutor;
use Illuminate\Support\Facades\Log;

class DkimService
{
    public function __construct(
        protected SudoExecutor $sudo,
        protected DnsService $dnsService,
    ) {}

    protected function dkimKeysPath(): string
    {
        return config('larapanel.mail.dkim_keys_path', '/etc/rspamd/dkim');
    }

    /**
     * Generate a 2048-bit RSA DKIM keypair for a domain.
     * Stores private key to disk, public key in DB.
     * Returns the DkimKey model.
     */
    public function generateKeyPair(Domain $domain, string $selector = 'mail'): DkimKey
    {
        // Deactivate any existing key for this selector
        DkimKey::where('domain_id', $domain->id)
            ->where('selector', $selector)
            ->update(['is_active' => false]);

        // Generate keypair using openssl (works in dev without sudo)
        $privateKeyPath = $this->getPrivateKeyPath($domain, $selector);

        if (app()->isProduction()) {
            $tmpDir = sys_get_temp_dir() . '/lp_dkim_' . uniqid();
            @mkdir($tmpDir, 0700, true);

            $tmpPriv = $tmpDir . '/private.key';
            $tmpPub  = $tmpDir . '/public.key';

            // Generate private key
            $this->sudo->run(['openssl', 'genrsa', '-out', $tmpPriv, '2048']);
            // Extract public key
            $this->sudo->run(['openssl', 'rsa', '-in', $tmpPriv, '-pubout', '-out', $tmpPub]);

            $privateKeyPem = file_get_contents($tmpPriv);
            $publicKeyPem  = file_get_contents($tmpPub);

            // Install private key to DKIM keys directory
            $this->sudo->run(['mkdir', '-p', $this->dkimKeysPath()]);
            $this->sudo->run(['cp', $tmpPriv, $privateKeyPath]);
            $this->sudo->run(['chmod', '640', $privateKeyPath]);
            $this->sudo->run(['chown', 'rspamd:rspamd', $privateKeyPath]);

            @unlink($tmpPriv);
            @unlink($tmpPub);
            @rmdir($tmpDir);
        } else {
            // Dev mode: generate with PHP OpenSSL extension
            $privKey = openssl_pkey_new([
                'private_key_bits' => 2048,
                'private_key_type' => OPENSSL_KEYTYPE_RSA,
            ]);

            openssl_pkey_export($privKey, $privateKeyPem);
            $keyDetails = openssl_pkey_get_details($privKey);
            $publicKeyPem = $keyDetails['key'];

            // Store in storage for dev
            $devPath = storage_path('app/public/dkim');
            @mkdir($devPath, 0700, true);
            file_put_contents($devPath . '/' . $domain->name . '.' . $selector . '.key', $privateKeyPem);
        }

        // Extract raw base64 public key (strip PEM headers for DNS TXT)
        $rawPublicKey = $this->extractRawPublicKey($publicKeyPem ?? '');

        // Build DNS TXT value
        $dnsValue = "v=DKIM1; k=rsa; p={$rawPublicKey}";

        $dkimKey = DkimKey::create([
            'domain_id'        => $domain->id,
            'selector'         => $selector,
            'private_key_path' => $privateKeyPath,
            'public_key'       => $rawPublicKey,
            'dns_value'        => $dnsValue,
            'key_size'         => 2048,
            'algorithm'        => 'rsa',
            'is_active'        => true,
        ]);

        AuditLog::record('dkim.generated', $domain->name, ['selector' => $selector]);

        return $dkimKey;
    }

    /**
     * Deploy DKIM key as DNS TXT record in the zone.
     */
    public function deployToDns(DkimKey $dkimKey, DnsZone $zone): void
    {
        $selector = $dkimKey->selector;
        $recordName = "{$selector}._domainkey";

        // Remove existing DKIM TXT records for this selector
        $existing = $zone->records()
            ->where('name', $recordName)
            ->where('type', 'TXT')
            ->get();

        foreach ($existing as $rec) {
            $this->dnsService->deleteRecord($rec);
        }

        // Add the new DKIM TXT record
        $this->dnsService->createRecord($zone, [
            'name'     => $recordName,
            'type'     => 'TXT',
            'content'  => $dkimKey->dns_value,
            'ttl'      => 3600,
            'priority' => 0,
            'comment'  => 'DKIM key generated by LaraPanel',
        ]);

        $dkimKey->update(['deployed_at' => now()]);

        AuditLog::record('dkim.deployed', $zone->name, ['selector' => $selector]);
    }

    /**
     * Configure Rspamd to use DKIM signing for this domain.
     */
    public function configureRspamdSigning(Domain $domain, DkimKey $dkimKey): void
    {
        if (!app()->isProduction()) {
            Log::info("DEV: Would configure Rspamd DKIM for {$domain->name}");
            return;
        }

        $confDir  = '/etc/rspamd/local.d';
        $confPath = $confDir . '/dkim_signing.conf';

        // Append or create Rspamd DKIM signing config
        $entry = "\n# {$domain->name}\ndomain {{\n  {$domain->name} {{\n    path = \"{$dkimKey->private_key_path}\";\n    selector = \"{$dkimKey->selector}\";\n  }}\n}}\n";

        $tmpFile = tempnam('/tmp', 'lp_dkim_conf_');
        $existing = file_exists($confPath) ? file_get_contents($confPath) : '';
        // Remove old entry for this domain if present
        $existing = preg_replace('/# ' . preg_quote($domain->name, '/') . '.*?}\s*}\s*/s', '', $existing);
        file_put_contents($tmpFile, $existing . $entry);

        $this->sudo->run(['cp', $tmpFile, $confPath]);
        $this->sudo->run(['chmod', '644', $confPath]);
        @unlink($tmpFile);

        // Reload Rspamd
        $this->sudo->run(['systemctl', 'reload', 'rspamd'], checkExit: false);
    }

    /**
     * Generate the recommended SPF TXT record for a domain.
     */
    public function generateSpfRecord(Domain $domain): string
    {
        $serverIp = config('larapanel.server.public_ip', '0.0.0.0');
        return "v=spf1 mx a ip4:{$serverIp} ~all";
    }

    /**
     * Generate DMARC TXT record.
     */
    public function generateDmarcRecord(Domain $domain, string $policy = 'none'): string
    {
        $policies = ['none', 'quarantine', 'reject'];
        if (!in_array($policy, $policies)) $policy = 'none';

        return "v=DMARC1; p={$policy}; rua=mailto:dmarc@{$domain->name}; ruf=mailto:dmarc@{$domain->name}; adkim=r; aspf=r; pct=100";
    }

    /**
     * Verify DKIM, SPF, DMARC records are correctly published in DNS.
     * Returns array with status per record type.
     */
    public function verifyAllRecords(Domain $domain): array
    {
        $results = [
            'dkim' => ['status' => 'unknown', 'value' => null, 'error' => null],
            'spf'  => ['status' => 'unknown', 'value' => null, 'error' => null],
            'dmarc'=> ['status' => 'unknown', 'value' => null, 'error' => null],
        ];

        if (!app()->isProduction()) {
            // Dev: simulate all OK
            $results['dkim']  = ['status' => 'ok', 'value' => 'v=DKIM1; k=rsa; p=MIIBIjAN...', 'error' => null];
            $results['spf']   = ['status' => 'ok', 'value' => 'v=spf1 mx a ip4:1.2.3.4 ~all',   'error' => null];
            $results['dmarc'] = ['status' => 'ok', 'value' => 'v=DMARC1; p=none; rua=mailto:dmarc@' . $domain->name, 'error' => null];
            return $results;
        }

        // DKIM
        try {
            $dkimKey = DkimKey::where('domain_id', $domain->id)->where('is_active', true)->first();
            if ($dkimKey) {
                $txtRecords = dns_get_record($dkimKey->selector . '._domainkey.' . $domain->name, DNS_TXT);
                $found = false;
                foreach ($txtRecords as $rec) {
                    $val = implode('', $rec['entries'] ?? [$rec['txt'] ?? '']);
                    if (str_contains($val, 'v=DKIM1')) {
                        $results['dkim'] = ['status' => 'ok', 'value' => $val, 'error' => null];
                        $found = true;
                        break;
                    }
                }
                if (!$found) $results['dkim']['status'] = 'missing';
            } else {
                $results['dkim']['status'] = 'not_configured';
            }
        } catch (\Throwable $e) {
            $results['dkim'] = ['status' => 'error', 'value' => null, 'error' => $e->getMessage()];
        }

        // SPF
        try {
            $txtRecords = dns_get_record($domain->name, DNS_TXT);
            $spfFound = false;
            foreach ($txtRecords as $rec) {
                $val = implode('', $rec['entries'] ?? [$rec['txt'] ?? '']);
                if (str_starts_with($val, 'v=spf1')) {
                    $results['spf'] = ['status' => 'ok', 'value' => $val, 'error' => null];
                    $spfFound = true;
                    break;
                }
            }
            if (!$spfFound) $results['spf']['status'] = 'missing';
        } catch (\Throwable $e) {
            $results['spf'] = ['status' => 'error', 'value' => null, 'error' => $e->getMessage()];
        }

        // DMARC
        try {
            $txtRecords = dns_get_record('_dmarc.' . $domain->name, DNS_TXT);
            $dmarcFound = false;
            foreach ($txtRecords as $rec) {
                $val = implode('', $rec['entries'] ?? [$rec['txt'] ?? '']);
                if (str_starts_with($val, 'v=DMARC1')) {
                    $results['dmarc'] = ['status' => 'ok', 'value' => $val, 'error' => null];
                    $dmarcFound = true;
                    break;
                }
            }
            if (!$dmarcFound) $results['dmarc']['status'] = 'missing';
        } catch (\Throwable $e) {
            $results['dmarc'] = ['status' => 'error', 'value' => null, 'error' => $e->getMessage()];
        }

        return $results;
    }

    protected function getPrivateKeyPath(Domain $domain, string $selector): string
    {
        return rtrim($this->dkimKeysPath(), '/') . '/' . $domain->name . '.' . $selector . '.key';
    }

    protected function extractRawPublicKey(string $pem): string
    {
        // Strip PEM headers and whitespace to get raw base64
        $pem = preg_replace('/-----BEGIN PUBLIC KEY-----|-----END PUBLIC KEY-----/', '', $pem);
        return preg_replace('/\s+/', '', $pem);
    }
}
