<?php
/**
 * Single Sign-On handler for phpMyAdmin.
 * Authenticates the user by verifying a token generated by LaraPanel.
 */

$tokenDir = sys_get_temp_dir() . DIRECTORY_SEPARATOR . 'larapanel_pma_sso';
$token = $_GET['token'] ?? '';

if (!preg_match('/^[a-zA-Z0-9]{40}$/', $token)) {
    die('Invalid or missing token.');
}

$tokenFile = $tokenDir . '/' . $token;

if (!file_exists($tokenFile)) {
    die('Token expired or invalid.');
}

// Read credentials (format: username:password)
$credentials = trim(file_get_contents($tokenFile));
@unlink($tokenFile); // Consume token

if (!$credentials || !str_contains($credentials, ':')) {
    die('Invalid credentials data.');
}

list($user, $password) = explode(':', $credentials, 2);

// Start PHP session for phpMyAdmin Signon
session_name('SignonSession');
session_start();

$_SESSION['PMA_single_signon_user'] = $user;
$_SESSION['PMA_single_signon_password'] = $password;

// Redirect to phpMyAdmin main page
header('Location: index.php');
exit;
